# MapirLiveTracker document generator jazzy settings

clean: true
copyright: Copyright 1398 Map
author: Map.ir
author_url: https://support.map.ir
xcodebuild_arguments: [-target, MapirLiveTracker-iOS]
output: ./Documentation
hide_documentation_coverage: YES

custom_categories:
- name: Publisher
  children:
    - Publisher
    - PublisherDelegate
    - Publisher.State
- name: Subscriber
  children:
    - Subscriber
    - SubscriberDelegate
- name: Networking
  children:
    - NetworkingManager
    - NetworkConfiguration
- name: Account
  children:
    - AccountManager
- name: Type Aliases
  children:
    - Meters
